# If the messages should try finding a text icon for this item from WolfieMarios Resourcepack (http://imgur.com/a/oHvbX)
texticonrp: false
# The default radius for the /showitem (/show, /si) command if no -r(adius) parameter is specified
defaultradius: 16
# Cooldown for the radius command in seconds. 
# 0 to disable cooldowns entirely. 
# Exempt permission: showitem.cooldownexempt
cooldown: 10
lang:
  radius:
    self: 'You hold up the item %item%!'
    custom: '&8(View distance: %radius%&8 blocks)'
    target: '%player% holds up the item %item%!'
  player:
    self: 'You show %player% the item %item%'
    target: '%player% shows you the item %item%'
  error:
    noitem: '&cYou don't have an item to show in your hand. :('
    playeroffline: '&cThe player %player%&c is not online'
    noonearound: '&cThere are no players around which could see your item :('
    coolden: '&cYou have to wait %remaining%&c more seconds before showing another item!'