# If the messages should try finding a text icon for this item from WolfieMarios Resourcepack (http://imgur.com/a/oHvbX)
texticonrp: false
# The default radius for the /showitem (/show, /si) command if no -r(adius) parameter is specified
defaultradius: 16
# Cooldown for the radius command in seconds. 
# 0 to disable cooldowns entirely. 
# Exempt permission: showitem.cooldownexempt
cooldown: 10
lang:
  radius:
    self: 'Du hälst dein Item %item% hoch!'
    custom: '&8(Sichtweite: %radius% Blöcke)'
    target: '%player% hält das Item %item% hoch!'
  player:
    self: 'Du zeigst %player% das Item %item%'
    target: '%player% zeigt dir das Item %item%'
  error:
    noitem: '&cDu hast kein Item in der Hand welches du zeigen könntest :('
    playeroffline: '&cDer Spieler %player% is nicht online'
    noonearound: '&cEs ist kein Spieler da um dein Item zu sehen :('
    coolden: '&cDu musst noch %remaining%s warten bevor du wieder ein Item zeigen kannst!'