# If the messages should try finding a text icon for this item from WolfieMarios Resourcepack (http://imgur.com/a/oHvbX)
texticonrp: false
# This option sets wether we should try to use the Bungee chat api when we detect a spigot server
# It does nothing on a normal craftbukkit
usefancymsg: true
# The default radius for the /showitem (/show, /si) command if no -r(adius) parameter is specified
defaultradius: 16
# Cooldowns for the radius and the direct show command in seconds.
# 0 to disable cooldowns entirely. 
# Exempt permission: showitem.cooldownexempt
cooldowns:
  all: 300
  world: 60
  radius: 10
  direct: 0
lang:
  all:
    self: "You show the item %item% to everyone!"
    target: "%player% shows everyone the item %item%!"
  world:
    self: "You show the item %item% to everyone in your world!"
    target: "%player% shows the item %item% to everyone in his world!"
  radius:
    self: "You hold up the item %item%!%customradius%"
    custom: "&8(View distance: %radius%&8 blocks)"
    target: "%player% holds up the item %item%!"
  player:
    self: "You show %player% the item %item%"
    target: "%player% shows you the item %item%"
  error:
    noitem: "&cYou don't have an item to show in your hand. :("
    playeroffline: "&cThe player %player%&c is not online"
    noonearound: "&cThere are no players around which could see your item :("
    cooldown: "&cYou have to wait %remaining%&c more seconds before showing another item!"