name: ShowItem
main: de.themoep.ShowItem.ShowItem
version: '${minecraft.plugin.version}'
description: ${project.description}
authors: [Phoenix616]
website: https://github.com/Phoenix616/ShowItem
commands:
   showitem:
      aliases: [si, show]
      description: Shows the item you are holding in your hand
      usage: /<command> [<player>]
      permission: showitem.command
      permission-message: You don't have the permission <permission>
permissions:
   showitem.command:
      description: Gives permission to the plugin command
      default: true
   showitem.command.player:
      description: Gives permission to show an item to a specific player wherever he is
      default: true
   showitem.command.radius:
      description: Gives permission to show an item in a radius you give
      default: op
   showitem.command.world:
      description: Gives permission to show an item to all players in his current world
      default: op
   showitem.command.all:
      description: Gives permission to show an item to all online players
      default: op
   showitem.command.reload:
      description: Gives permission to use the reload command
      default: op
   showitem.command.debug:
      description: Gives permission to use the debug command
      default: op
   showitem.cooldownexempt:
      description: Gives permission to bypass the command cooldowns
      default: op
