defaultradius: 16
lang:
  radius:
    self: 'Du hälst dein Item %item% hoch! &8(Sichtweite: %radius% &8Blöcke)'
    target: '%player% hält das Item %item% hoch!'
    noone: '&cEs ist kein Spieler da um dein Item zu sehen :('
  player:
    self: 'Du zeigst %player% das Item %item%'
    target: '%player% zeigt dir das Item %item%'
    offline: 'Der Spieler %player% is nicht online'
idmapping:
  SKULL_ITEM:
    mc: skull
  WOOD_DOOR:
    mc: wooden_door
  FIREWORK:
    mc: fireworks
  GOLD_HELMET:
    mc: golden_helmet
  GOLD_CHESTPLATE:
    mc: golden_chestplate
  GOLD_LEGGINGS:
    mc: golden_leggings
  GOLD_BOOTS:
    mc: golden_boots
  MONSTER_EGG:
    mc: spawn_egg
  EXP_BOTTLE:
    mc: experience_bottle
    alias: Bottle o' Enchanting
  BOOK_AND_QUILL:
    mc: writable_book
    alias: Book and Quill
  EYE_OF_ENDER:
    mc: ender_eye
    alias: Eye of Ender
  SPECKLED_MELON:
    mc: speckled_melon
    alias: Glistering Melon
  FLINT_AND_STEEL:
    mc: flint_and_steel
  EMPTY_MAP:
    mc: map
    alias: Empty Map
  GOLD_RECORD:
    mc: record_13
  GREEN_RECORD:
    mc: record_cat
  RECORD_3:
    mc: record_blocks
  RECORD_4:
    mc: record_chirp
  RECORD_5:
    mc: record_far
  RECORD_6:
    mc: record_mall
  RECORD_7:
    mc: record_mellohi
  RECORD_8:
    mc: record_stal
  RECORD_9:
    mc: record_strad
  RECORD_10:
    mc: record_ward
  RECORD_12:
    mc: record_wait
  ENDER_PORTAL_FRAME:
    mc: end_portal_frame
  RED_ROSE:
    mc: red_flower
  WATER_LILY:
    mc: waterlily
    alias: Lily Pad
  WEB:
    alias: Cobweb
  MONSTER_EGGS:
    mc: monster_egg
    alias: Monster Egg Stone
  THIN_GLASS:
    mc: glass_pane
  ENCHANTMENT_TABLE:
    mc: enchanting_table
  FENCE:
    alias: Oak Fence
  SLIME_BLOCK:
    mc: slime
    alias: Slime Block
  LEAVES_2:
    mc: leaves2
  LOG_2:
    mc: log2
  GRASS:
    alias: Grass Block
  WOOD:
    mc: planks
    alias: Wood Planks
  ENDER_STONE:
    mc: end_stone
  MYCEL:
    mc: mycelium
  BRICK:
    mc: brick_block
  CLAY_BRICK:
    mc: brick
    alias: Clay Brick
  HARD_CLAY:
    mc: hardened_clay
  STAINED_GLAY:
    mc: stained_hardened_clay
    alias: Stained Clay
  COBBLESTONE_STAIRS:
    mc: stone_stairs
    alias: Cobblestone Stairs
  COBBLE_WALL:
    mc: cobblestone_wall
  STEP:
    mc: stone_slab
  WOOD_STEP:
    mc: wooden_slab
    alias: Wood Slab
  WOOD_STAIRS:
    mc: oak_stairs
  SMOOTH_STAIRS:
    mc: stone_brick_stairs
  SPRUCE_WOOD_STAIRS:
    mc: spruce_stairs
    alias: Spruce Wood Stairs
  BIRCH_WOOD_STAIRS:
    mc: birch_stairs
    alias: Birch Wood Stairs
  JUNGLE_WOOD_STAIRS:
    mc: jungle_stairs
    alias: Jungle Wood Stairs
  ACACIA_STAIRS:
    alias: Acacia Wood Stairs
  DARK_OAK_STAIRS:
    alias: Dark Oak Wood Stairs
  HAY_BLOCK:
    alias: Hay Bale
  LONG_GRASS:
    mc: tallgrass
  DEAD_BUSH:
    mc: deadbush
    alias: Dead Bush
  WORKBENCH:
    mc: crafting_table
    alias: Workbench
  SNOW:
    mc: snow_layer
  SNOW_BLOCK:
    mc: snow
    alias: Snow Block
  DIODE:
    mc: repeater
    alias: Redstone Repeater
  REDSTONE_COMPARATOR:
    mc: comparator
    alias: Redstone Comparator
  WOOD_BUTTON:
    mc: wooden_button
  GOLD_PLATE:
    mc: light_weighted_pressure_plate
  IRON_PLATE:
    mc: heavy_weighted_pressure_plate
  DAYLIGHT_DETECTOR:
    alias: Daylight Sensor
  POWERED_RAIL:
    mc: golden_rail
    alias: Powered Rail
  RAILS:
    mc: rail
  STORAGE_MINECART:
    mc: chest_minecart
  POWERED_MINECART:
    mc: furnace_minecart
  EXPLOSIVE_MINECART:
    mc: tnt_minecart
    alias: TNT Minecart
  CARROT_STICK:
    mc: carrot_on_a_stick
    alias: Carrot on a Stick
  IRON_BARDING:
    mc: iron_horse_armor
  GOLD_BARDING:
    mc: golden_horse_armor
    alias: Golden Horse Armor
  DIAMOND_BARDING:
    mc: diamond_horse_armor
  FIREBALL:
    mc: fire_charge
  RAW_FISH:
    mc: fish
    alias: Raw Fish
  PORK:
    mc: porkchop
    alias: Raw Porkchop
  JACK_O_LANTER:
    mc: lit_pumpkin
    alias: "Jack o'Lantern"
  MUSHROOM_SOUP:
    mc: mushroom_stew
  RAW_BEEF:
    mc: beef
    alias: Raw Beef
  RAW_CHICKEN:
    mc: chicken
    alias: Raw Chicken
  RABBIT:
    alias: Raw Rabbit
  MUTTON:
    alias: Raw Mutton
  RAW_BEEF:
    mc: beef
    alias: Raw Beef
  LEASH:
    mc: lead
  WATCH:
    mc: clock
  INK_SACK:
    mc: dye
    alias: Dye
  NETHER_STALK:
    mc: nether_wart